/**
 * employee_history.js
 * Handles fetching and displaying payroll and leave history for a specific employee.
 */

if (!requireAuth()) { /* redirects handled inside */ }

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

document.addEventListener('DOMContentLoaded', async () => {
    const urlParams = new URLSearchParams(window.location.search);
    const empId = urlParams.get('id');
    const tabId = urlParams.get('tab'); // 'payroll' or 'leave'

    if (!empId) {
        API.showToast("No Employee ID provided", "danger");
        window.location.href = 'dashboard.html';
        return;
    }

    // Isolate View: Hide the 'other' tab and its content
    const tabs = document.getElementById('historyTabs');
    if (tabId === 'payroll') {
        document.getElementById('pageTitle').textContent = 'EMPLOYEE PAYROLL HISTORY';
        document.getElementById('leave-tab')?.parentElement?.remove();
        document.getElementById('leaveSection')?.remove();
        tabs.style.display = 'none'; // Only one tab left
    } else if (tabId === 'leave') {
        document.getElementById('pageTitle').textContent = 'EMPLOYEE LEAVE HISTORY';
        document.getElementById('payroll-tab')?.parentElement?.remove();
        document.getElementById('payrollSection')?.remove();
        
        const leaveTab = document.getElementById('leave-tab');
        if (leaveTab) bootstrap.Tab.getOrCreateInstance(leaveTab).show();
        tabs.style.display = 'none'; // Only one tab left
    }

    try {
        // Only fetch required data
        const empPromise      = API.get(`/api/employees/${empId}`);
        const payrollPromise  = tabId === 'payroll' ? API.get(`/api/payroll?employee_id=${empId}`) : Promise.resolve([]);
        const leavePromise    = tabId === 'leave' ? API.get('/api/leave') : Promise.resolve([]);

        const [emp, payrolls, leaves] = await Promise.all([empPromise, payrollPromise, leavePromise]);

        renderHeader(emp);
        if (tabId === 'payroll') renderPayrollHistory(payrolls);
        if (tabId === 'leave')   renderLeaveHistory(leaves.filter(l => l.employee_id === empId));

    } catch (err) {
        API.showToast(err.message || "Failed to load history", "danger");
    }
});

function renderHeader(emp) {
    const name = [emp.first_name, emp.middle_name, emp.last_name].filter(Boolean).join(' ');
    document.getElementById('histEmpName').textContent = name || 'Unknown Employee';
    document.getElementById('histEmpId').textContent   = emp.employee_id || emp.id;
}

function renderPayrollHistory(payrolls) {
    const listEl = document.getElementById('payrollList');
    const user = getCurrentUser();

    if (!payrolls.length) {
        listEl.innerHTML = '<div class="text-dim text-center py-5"><i class="bi bi-inbox fs-2 d-block mb-2"></i>No payroll records found.</div>';
        return;
    }

    // Sort by period (latest first)
    payrolls.sort((a,b) => {
        if (a.period_year !== b.period_year) return b.period_year - a.period_year;
        return (b.period_month || 1) - (a.period_month || 1);
    });

    listEl.innerHTML = payrolls.map(rec => {
        const monthName = MONTHS[(rec.period_month || 1) - 1] + ' ' + rec.period_year;
        const netFmt    = parseFloat(rec.net_salary || 0).toLocaleString('en-PH', { minimumFractionDigits: 2 });
        const dateFmt   = rec.created_at ? new Date(rec.created_at).toLocaleDateString('en-PH') : '';
        
        return `
        <div class="history-item d-flex justify-content-between align-items-center" onclick='viewPayslipDetails(${JSON.stringify(rec).replace(/'/g, "&apos;")})'>
            <div>
                <div class="text-white fw-bold">${monthName}</div>
                <div class="text-dim small">${dateFmt} &bull; Generated by: ${rec.generated_by || 'System'}</div>
            </div>
            <div class="text-end d-flex align-items-center gap-3">
                <div class="text-end">
                    <div class="net-pay">PHP ${netFmt}</div>
                    <div class="text-dim x-small">Click to view details</div>
                </div>
                ${user.role !== 'employee' ? `
                <button class="btn btn-link text-danger p-0" 
                    onclick="deletePayroll(${rec.id}, event)" 
                    title="Delete Record">
                    <i class="bi bi-trash"></i>
                </button>` : ''}
            </div>
        </div>`;
    }).join('');
}

function renderLeaveHistory(leaves) {
    const listEl = document.getElementById('leaveList');
    if (!leaves.length) {
        listEl.innerHTML = '<div class="text-dim text-center py-5"><i class="bi bi-calendar-x fs-2 d-block mb-2"></i>No leave requests found.</div>';
        return;
    }

    // Sort by id (latest first)
    leaves.sort((a,b) => b.id - a.id);

    listEl.innerHTML = leaves.map(l => {
        const statusClass = `badge-${l.status.toLowerCase()}`;
        return `
        <div class="history-item mb-3">
            <div class="d-flex justify-content-between align-items-start">
                <div>
                    <span class="badge border border-light text-light px-2 py-1 mb-2">${l.leave_type}</span>
                    <div class="text-white fw-bold">${l.date_from} <i class="bi bi-arrow-right mx-1"></i> ${l.date_to}</div>
                    <div class="text-dim small mt-1">${l.reason || 'No reason provided'}</div>
                </div>
                <div class="text-end">
                    <span class="leave-badge ${statusClass}">${l.status}</span>
                    <div class="text-dim x-small mt-2">Request ID: #${l.id}</div>
                </div>
            </div>
        </div>`;
    }).join('');
}

function viewPayslipDetails(rec) {
    const modalBody = document.getElementById('payslipModalBody');
    const monthName = MONTHS[(rec.period_month || 1) - 1] + ' ' + rec.period_year;
    const fmtNum = n => parseFloat(n || 0).toLocaleString('en-PH', { minimumFractionDigits: 2 });
    const user = getCurrentUser();
    
    modalBody.innerHTML = `
    <div class="text-center mb-4">
        <h4 class="text-white">Official Payslip</h4>
        <div class="text-dim">${monthName}</div>
    </div>
    <div class="row mb-3">
        <div class="col-6 text-dim small">Employee ID:</div>
        <div class="col-6 text-white text-end">${rec.employee_id}</div>
    </div>
    <hr class="border-secondary">
    <div class="row mb-2">
        <div class="col-6 text-white">Base Salary</div>
        <div class="col-6 text-white text-end">PHP ${fmtNum(rec.base_salary)}</div>
    </div>
    <div class="row mb-2">
        <div class="col-6 text-success">Attendance Bonus (${rec.work_days} days)</div>
        <div class="col-6 text-success text-end">+ PHP ${fmtNum(rec.allowance)}</div>
    </div>
    <div class="row mb-2">
        <div class="col-6 text-danger">Standard Deductions</div>
        <div class="col-6 text-danger text-end">- PHP ${fmtNum(rec.deductions)}</div>
    </div>
    <div class="row mb-2">
        <div class="col-6 text-danger">Leave Deductions</div>
        <div class="col-6 text-danger text-end">- PHP ${fmtNum(rec.leave_deductions)}</div>
    </div>
    <div class="row mb-2">
        <div class="col-6 text-danger">Tax (10%)</div>
        <div class="col-6 text-danger text-end">- PHP ${fmtNum(rec.tax)}</div>
    </div>
    <hr class="border-secondary">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <div class="text-white fs-5 fw-bold">NET PAY</div>
        <div class="text-success fs-4 fw-bold">PHP ${fmtNum(rec.net_salary)}</div>
    </div>
    
    ${user.role !== 'employee' ? `
    <div class="text-center mt-3 pt-3 border-top border-secondary">
        <button class="btn btn-outline-danger btn-sm" onclick="deletePayroll(${rec.id}, null, true)">
            <i class="bi bi-trash me-1"></i> Delete This Record
        </button>
    </div>` : ''}
    `;
    
    const modal = new bootstrap.Modal(document.getElementById('payslipModal'));
    modal.show();
}

async function deletePayroll(id, event, isFromModal = false) {
    if (event) event.stopPropagation();
    
    if (!confirm('Are you sure you want to delete this payroll record?')) return;

    try {
        await API.delete(`/api/payroll/${id}`);
        API.showToast('Payroll record deleted', 'success');
        
        if (isFromModal) {
            const modalEl = document.getElementById('payslipModal');
            const modal = bootstrap.Modal.getInstance(modalEl);
            if (modal) modal.hide();
        }
        
        // Reload page data
        const urlParams = new URLSearchParams(window.location.search);
        const empId = urlParams.get('id');
        const payrolls = await API.get(`/api/payroll?employee_id=${empId}`);
        renderPayrollHistory(payrolls);
        
    } catch (err) {
        API.showToast(err.message || 'Failed to delete record', 'danger');
    }
}
